### ISSUE TITLE
fix truffle tests against geth node

### ISSUE THREAD

**Issue by manuelpolzhofer** [centrifuge/centrifuge-ethereum-contracts#56]
Currently, 13 tests are failing if we run the truffle tests against a local geth node instead of ganache.

For example `geth` handles `revert` transaction with different error messages compared to ganache.
Which is responsible for some of the failures.

**Comment by manuelpolzhofer** [comment]
```bash
➜  centrifuge-ethereum-contracts git:(develop) ✗ npm run test -- --network localgeth

> @centrifuge/ethereum-contracts@0.2.2 test /Users/manuelpolzhofer/go/src/github.com/centrifuge/centrifuge-ethereum-contracts
> truffle test "--network" "localgeth"

Using network 'localgeth'.

Compiling ./contracts/AnchorRepository.sol...
Compiling ./contracts/Identity.sol...
Compiling ./contracts/IdentityFactory.sol...
Compiling ./contracts/IdentityRegistry.sol...
Compiling ./contracts/KeyManager.sol...
Compiling ./contracts/erc721/PaymentObligation.sol...
Compiling ./contracts/erc721/UserMintableERC721.sol...
Compiling ./contracts/lib/MerkleProofSha256.sol...
Compiling contracts/AnchorRepository.sol...
Compiling contracts/Identity.sol...
Compiling contracts/IdentityRegistry.sol...
Compiling contracts/KeyManager.sol...
Compiling contracts/erc721/UserMintableERC721.sol...
Compiling contracts/lib/MerkleProofSha256.sol...
Compiling openzeppelin-solidity/contracts/AddressUtils.sol...
Compiling openzeppelin-solidity/contracts/ECRecovery.sol...
Compiling openzeppelin-solidity/contracts/MerkleProof.sol...
Compiling openzeppelin-solidity/contracts/introspection/ERC165.sol...
Compiling openzeppelin-solidity/contracts/introspection/SupportsInterfaceWithLookup.sol...
Compiling openzeppelin-solidity/contracts/math/SafeMath.sol...
Compiling openzeppelin-solidity/contracts/ownership/Ownable.sol...
Compiling openzeppelin-solidity/contracts/token/ERC721/ERC721.sol...
Compiling openzeppelin-solidity/contracts/token/ERC721/ERC721Basic.sol...
Compiling openzeppelin-solidity/contracts/token/ERC721/ERC721BasicToken.sol...
Compiling openzeppelin-solidity/contracts/token/ERC721/ERC721Receiver.sol...
Compiling openzeppelin-solidity/contracts/token/ERC721/ERC721Token.sol...

Compilation warnings encountered:

/Users/manuelpolzhofer/go/src/github.com/centrifuge/centrifuge-ethereum-contracts/contracts/erc721/PaymentObligation.sol:2:1: Warning: Experimental features are turned on. Do not use experimental features on live deployments.
pragma experimental ABIEncoderV2;
^-------------------------------^



  Contract: AnchorRegistry
    Anchor Creation
      1) should only allow fully filled anchors to be recorded
    > No events were emitted
      ✓ should write a merkle root to the chain and be able to read it (2032ms)
      2) should not be able to overwrite existing anchor

    Events emitted during test:
    ---------------------------

    AnchorRegistered(from: <indexed>, identifier: <indexed>, rootHash: <indexed>, timestamp: 0x000000000000000000000000000000000000000000000000000000005bd9a8f9, anchorSchemaVersion: 1)

    ---------------------------
      ✓ should return an empty anchor for wrong identifier

  Contract: AnchorRepository
    3) "before all" hook

  Contract: Identity
    Identity Creation
      ✓ should create identity (2047ms)
      4) should not create identity if centrifugeId is 0x0, null, empty
    > No events were emitted
    Should Validate a signature
      5) should validate a web3 signature
    > No events were emitted
      ✓ should validate a signature generated with go-centrifuge (2036ms)
      ✓ should be false because of an invalid signature (2028ms)

  Contract: IdentityFactory
    Create Identity
      6) should register identity and transfer ownership
    > No events were emitted
      7) should register identity once
    > No events were emitted
      ✓ should not register identity if arguments malformed (4042ms)

  Contract: IdentityRegistry
    Register Identity
      ✓ should register identity (2021ms)
      ✓ should not register identity if function arguments are malformed (6066ms)
      ✓ should not register identity if centrifugeId already exists (4038ms)
    Update Identity Address
      ✓ should update identity address with same owner (4035ms)
      8) should not update identity address with different owner

    Events emitted during test:
    ---------------------------

    IdentityRegistered(centrifugeId: <indexed>, identity: 0xd78703537f7b71ea377ed2f1463162b700000000)

    ---------------------------
      ✓ should not update identity with malformed arguments (2022ms)
    Retrieve Identity Address
      ✓ should retrieve identity address from centrifuge id by anyone (2024ms)
      ✓ should return 0x0 if identity not found

  Contract: KeyManager
    Adding/Retrieving Keys
      ✓ Should not add a empty key (6075ms)
      ✓ Should not add a key with an empty purpose (6080ms)
      9) should not allow adding a key if the sender is not the owner
    > No events were emitted
      ✓ Should add a key with both P2P_IDENTITY and P2P_SIGNATURE purposes and retrieve it (4062ms)
      ✓ should add the same purpose only one time to a key (8103ms)
      ✓ Should not find a key (2035ms)
      ✓ Should revert if trying to revoke an unexisting key (4059ms)
      ✓ Should revoke a key (6086ms)
      ✓ Should add and retrieve keys by purpose (8142ms)
    Event dispatching
      ✓ Should dispatch a KeyAdded event (3552ms)
      ✓ Should dispatch a KeyRevoked event (6085ms)
      ✓ Should dispatch a KeyAdded event (4059ms)
      ✓ Should dispatch 3 KeyAdded events in a specific order (4067ms)
      ✓ Should dispatch 1 KeyAdded event because one purpose existed (6076ms)
    Check Gas
Actual addMultiPurposeKey gas cost: 179331
      ✓  Gas cost for adding a key with 3 purposes should be less then 250000  (2043ms)
Actual AddKey gas cost: 108100
      ✓  Gas cost for adding a key with one purpose should be less then 120000  (2045ms)
Actual revokeKey gas cost: 46310
      ✓  Gas cost for revoking a key should be less then 50000  (3562ms)

  Contract: UserMintableERC721
    UserMintableERC721
      ✓ should be deployable as an independent registry (4079ms)
      ✓ should be able to check if documents are registered on the anchor registry (4079ms)
    _hashLeafData
      ✓ should hash the leaf data the same way JS does (2040ms)
    mintAnchor
      ✓ should mint a token if the Merkle proof validates (4058ms)
      ✓ should fail minting a token if the document idenfitier is not found (6084ms)

  Contract: PaymentObligation
    mint
0x891244e3c3c6c634661ecc86d75fc405ec1f88012eacc209e10b12a8a11727fb
      10) should mint a token if the Merkle proofs validates
    > No events were emitted
      11) should not mint a token if the a Merkle proof fails
    > No events were emitted
      12) should not mint a token if the anchorId has been used before
    > No events were emitted
    check the gas cost for mint
      13) should have mint gas cost less then 533819 
    > No events were emitted


  34 passing (5m)
  13 failing

  1) Contract: AnchorRegistry
       Anchor Creation
         should only allow fully filled anchors to be recorded:

      AssertionError: expected 'Transaction: 0x109cca3f53d0e576985d6d7706cc96c69d432e3be72ee498c2f257b760bb30eb exited with an error (status 0).\nPlease check that the transaction:\n    - satisfies all conditions set by Solidity `require` statements.\n    - does not trigger a Solidity `revert` statement.\n' to equal 'VM Exception while processing transaction: revert'
      + expected - actual

      -Transaction: 0x109cca3f53d0e576985d6d7706cc96c69d432e3be72ee498c2f257b760bb30eb exited with an error (status 0).
      -Please check that the transaction:
      -    - satisfies all conditions set by Solidity `require` statements.
      -    - does not trigger a Solidity `revert` statement.
      +VM Exception while processing transaction: revert
      
      at test/AnchorRegistry.test.js:33:24
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  2) Contract: AnchorRegistry
       Anchor Creation
         should not be able to overwrite existing anchor:

      AssertionError: expected 'Transaction: 0xed4d760ec814b67394e3d0659d2c525ff054a9767fdc506cfee3cf7c662a4153 exited with an error (status 0).\nPlease check that the transaction:\n    - satisfies all conditions set by Solidity `require` statements.\n    - does not trigger a Solidity `revert` statement.\n' to equal 'VM Exception while processing transaction: revert'
      + expected - actual

      -Transaction: 0xed4d760ec814b67394e3d0659d2c525ff054a9767fdc506cfee3cf7c662a4153 exited with an error (status 0).
      -Please check that the transaction:
      -    - satisfies all conditions set by Solidity `require` statements.
      -    - does not trigger a Solidity `revert` statement.
      +VM Exception while processing transaction: revert
      
      at test/AnchorRegistry.test.js:97:24
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  3) Contract: AnchorRepository
       "before all" hook:
     Error: Invalid number of arguments to Solidity function
      at Object.InvalidNumberOfSolidityArgs (node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:25:1)
      at SolidityFunction.validateArgs (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:74:1)
      at SolidityFunction.toPayload (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:90:1)
      at SolidityFunction.sendTransaction (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:163:1)
      at SolidityFunction.execute (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:256:1)
      at node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:204:1
      at new Promise (<anonymous>)
      at node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:155:1
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  4) Contract: Identity
       Identity Creation
         should not create identity if centrifugeId is 0x0, null, empty:
     AssertionError: Expected "revert", got Error: The contract code couldn't be stored, please check your gas amount. instead
      at _callee2$ (test/tools/assertTx.js:11:9)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as throw] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/tools/assertTx.js:3:191)
      at test/tools/assertTx.js:3:402
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  5) Contract: Identity
       Should Validate a signature
         should validate a web3 signature:
     Error: Invalid number of arguments to Solidity function
      at Object.InvalidNumberOfSolidityArgs (node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:25:1)
      at SolidityFunction.validateArgs (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:74:1)
      at SolidityFunction.toPayload (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:90:1)
      at SolidityFunction.sendTransaction (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:163:1)
      at SolidityFunction.execute (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:256:1)
      at node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:204:1
      at new Promise (<anonymous>)
      at node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:155:1
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  6) Contract: IdentityFactory
       Create Identity
         should register identity and transfer ownership:
     Error: invalid address
      at inputAddressFormatter (node_modules/truffle/build/webpack:/~/web3/lib/web3/formatters.js:274:1)
      at inputTransactionFormatter (node_modules/truffle/build/webpack:/~/web3/lib/web3/formatters.js:100:1)
      at node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:89:1
      at Array.map (<anonymous>)
      at Method.formatInput (node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:88:1)
      at Method.toPayload (node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:114:1)
      at Eth.send [as sendTransaction] (node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:139:1)
      at SolidityFunction.sendTransaction (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:173:1)
      at SolidityFunction.execute (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:256:1)
      at node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:204:1
      at new Promise (<anonymous>)
      at node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:155:1
      at <anonymous>

  7) Contract: IdentityFactory
       Create Identity
         should register identity once:
     Error: invalid address
      at inputAddressFormatter (node_modules/truffle/build/webpack:/~/web3/lib/web3/formatters.js:274:1)
      at inputTransactionFormatter (node_modules/truffle/build/webpack:/~/web3/lib/web3/formatters.js:100:1)
      at node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:89:1
      at Array.map (<anonymous>)
      at Method.formatInput (node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:88:1)
      at Method.toPayload (node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:114:1)
      at Eth.send [as sendTransaction] (node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:139:1)
      at SolidityFunction.sendTransaction (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:173:1)
      at SolidityFunction.execute (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:256:1)
      at node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:204:1
      at new Promise (<anonymous>)
      at node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:155:1
      at <anonymous>

  8) Contract: IdentityRegistry
       Update Identity Address
         should not update identity address with different owner:
     AssertionError: Expected "revert", got Error: invalid address instead
      at _callee2$ (test/tools/assertTx.js:11:9)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as throw] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/tools/assertTx.js:3:191)
      at test/tools/assertTx.js:3:402
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  9) Contract: KeyManager
       Adding/Retrieving Keys
         should not allow adding a key if the sender is not the owner:
     AssertionError: Expected "revert", got Error: invalid address instead
      at _callee2$ (test/tools/assertTx.js:11:9)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as throw] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/tools/assertTx.js:3:191)
      at test/tools/assertTx.js:3:402
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  10) Contract: PaymentObligation
       mint
         should mint a token if the Merkle proofs validates:
     Error: invalid address (arg="_to", coderType="address", value=undefined)
      at Object.throwError (node_modules/ethers/utils/errors.js:68:17)
      at CoderAddress.encode (node_modules/ethers/utils/abi-coder.js:467:20)
      at node_modules/ethers/utils/abi-coder.js:605:59
      at Array.forEach (<anonymous>)
      at pack (node_modules/ethers/utils/abi-coder.js:604:12)
      at CoderTuple.encode (node_modules/ethers/utils/abi-coder.js:764:16)
      at AbiCoder.encode (node_modules/ethers/utils/abi-coder.js:897:77)
      at ABICoder.encodeParameters (node_modules/web3-eth-abi/src/index.js:96:27)
      at node_modules/web3-eth-contract/src/index.js:426:24
      at Array.map (<anonymous>)
      at Object._encodeMethodABI (node_modules/web3-eth-contract/src/index.js:425:12)
      at Object._processExecuteArguments (node_modules/web3-eth-contract/src/index.js:741:39)
      at Object._executeMethod (node_modules/web3-eth-contract/src/index.js:766:54)
      at Context._callee3$ (test/erc721/PaymentObligation.test.js:80:15)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/erc721/PaymentObligation.test.js:5:191)
      at test/erc721/PaymentObligation.test.js:5:361
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  11) Contract: PaymentObligation
       mint
         should not mint a token if the a Merkle proof fails:
     Error: invalid address (arg="_to", coderType="address", value=undefined)
      at Object.throwError (node_modules/ethers/utils/errors.js:68:17)
      at CoderAddress.encode (node_modules/ethers/utils/abi-coder.js:467:20)
      at node_modules/ethers/utils/abi-coder.js:605:59
      at Array.forEach (<anonymous>)
      at pack (node_modules/ethers/utils/abi-coder.js:604:12)
      at CoderTuple.encode (node_modules/ethers/utils/abi-coder.js:764:16)
      at AbiCoder.encode (node_modules/ethers/utils/abi-coder.js:897:77)
      at ABICoder.encodeParameters (node_modules/web3-eth-abi/src/index.js:96:27)
      at node_modules/web3-eth-contract/src/index.js:426:24
      at Array.map (<anonymous>)
      at Object._encodeMethodABI (node_modules/web3-eth-contract/src/index.js:425:12)
      at Object._processExecuteArguments (node_modules/web3-eth-contract/src/index.js:741:39)
      at Object._executeMethod (node_modules/web3-eth-contract/src/index.js:766:54)
      at Context._callee4$ (test/erc721/PaymentObligation.test.js:142:15)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/erc721/PaymentObligation.test.js:5:191)
      at test/erc721/PaymentObligation.test.js:5:361
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  12) Contract: PaymentObligation
       mint
         should not mint a token if the anchorId has been used before:
     Error: invalid address (arg="_to", coderType="address", value=undefined)
      at Object.throwError (node_modules/ethers/utils/errors.js:68:17)
      at CoderAddress.encode (node_modules/ethers/utils/abi-coder.js:467:20)
      at node_modules/ethers/utils/abi-coder.js:605:59
      at Array.forEach (<anonymous>)
      at pack (node_modules/ethers/utils/abi-coder.js:604:12)
      at CoderTuple.encode (node_modules/ethers/utils/abi-coder.js:764:16)
      at AbiCoder.encode (node_modules/ethers/utils/abi-coder.js:897:77)
      at ABICoder.encodeParameters (node_modules/web3-eth-abi/src/index.js:96:27)
      at node_modules/web3-eth-contract/src/index.js:426:24
      at Array.map (<anonymous>)
      at Object._encodeMethodABI (node_modules/web3-eth-contract/src/index.js:425:12)
      at Object._processExecuteArguments (node_modules/web3-eth-contract/src/index.js:741:39)
      at Object._executeMethod (node_modules/web3-eth-contract/src/index.js:766:54)
      at Context._callee5$ (test/erc721/PaymentObligation.test.js:185:15)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/erc721/PaymentObligation.test.js:5:191)
      at test/erc721/PaymentObligation.test.js:5:361
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  13) Contract: PaymentObligation
       check the gas cost for mint
         should have mint gas cost less then 533819 :
     Error: invalid address (arg="_to", coderType="address", value=undefined)
      at Object.throwError (node_modules/ethers/utils/errors.js:68:17)
      at CoderAddress.encode (node_modules/ethers/utils/abi-coder.js:467:20)
      at node_modules/ethers/utils/abi-coder.js:605:59
      at Array.forEach (<anonymous>)
      at pack (node_modules/ethers/utils/abi-coder.js:604:12)
      at CoderTuple.encode (node_modules/ethers/utils/abi-coder.js:764:16)
      at AbiCoder.encode (node_modules/ethers/utils/abi-coder.js:897:77)
      at ABICoder.encodeParameters (node_modules/web3-eth-abi/src/index.js:96:27)
      at node_modules/web3-eth-contract/src/index.js:426:24
      at Array.map (<anonymous>)
      at Object._encodeMethodABI (node_modules/web3-eth-contract/src/index.js:425:12)
      at Object._processExecuteArguments (node_modules/web3-eth-contract/src/index.js:741:39)
      at Object._executeMethod (node_modules/web3-eth-contract/src/index.js:766:54)
      at Context._callee7$ (test/erc721/PaymentObligation.test.js:262:15)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/erc721/PaymentObligation.test.js:5:191)
      at test/erc721/PaymentObligation.test.js:5:361
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

```
